# Generated by Django 5.1.3 on 2024-11-15 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Mascota')),
                ('species', models.CharField(choices=[('Dog', 'Perro'), ('Cat', 'Gato'), ('Other', 'Otro')], max_length=50, verbose_name='Especie')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Raza')),
                ('last_seen_location', models.CharField(max_length=255, verbose_name='Última vez visto')),
                ('last_seen_date', models.DateField(verbose_name='Último día visto')),
                ('contact_info', models.CharField(max_length=100, verbose_name='Información de contacto')),
                ('additional_details', models.TextField(blank=True, null=True, verbose_name='Detalles adicionales')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/', verbose_name='Foto de la mascota')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_pets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mascota perdida',
                'verbose_name_plural': 'Mascotas perdidas',
            },
        ),
    ]
